### PR TITLE
Make Bigstring_unix independent of Bigstring

### PR DESCRIPTION
**Pull request by madroach**
also remove the unnecessary dependency on base-bytes

### CODE REVIEW

**Review by c-cube — CHANGES_REQUESTED** [review]
This seems like a good idea! I'd just like an `@since` annotation on the `type t = …` in the mli.

**Comment by madroach** [comment]
Added ``@since`` annotation.
Is the ``.merlin`` file in the repository by accident or on purpose? It is also mentioned in ``.gitignore``.

**Comment by c-cube** [comment]
the .merlin is probably there by accident.

**Comment by c-cube** [comment]
Thanks a lot :100:

**Pull request merged**
